### ISSUE TITLE
Output files

### ISSUE THREAD

**Issue by hayesall** [boost-starai/NLP-Preprocessing#9]
Present implementation appends facts, blocks, sentences, etc. to files in the user's current directory.

Ideally there should be an output flag (`-o`) with which users may specify where these should be written to.

**Comment by adamjsawicki** [comment]
If `-o` is specified, should all writing be done to that file regardless of whether it's a fact, block, sentence, etc?

**Comment by hayesall** [comment]
Currently this outputs four files (see [`parse.py`](https://github.com/hayesall/rnlp/blob/10ecea4addc063f89b4bfea0f918794f6cf05c44/rnlp/parse.py))

I think a `-o` flag would be helpful for pre-pending a path, for example: `-o financial_documents/` would write `financial_documents/facts.txt`, `financial_documents/blockIDs.txt`, etc.

@Swixx do you think separate output flags for each file would be more useful?

**Comment by adamjsawicki** [comment]
No, I think that overcomplicates things without a good use case, but I'm willing to be convinced.

**Comment by hayesall** [comment]
100% agree. I think your solution in #21 is on the right track!

I can imagine some cases where we include/exclude specific output files, but this seems like a premature optimization.
